
# Logistic Regression

In [3]:
import pandas as pd
import numpy as np
from sklearn import preprocessing 
import matplotlib.pyplot as plt


In [5]:
data = pd.read_csv("C:\\Users\\CTS\\Downloads\\ChurnData.csv")
data.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...    pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...      1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...      0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...      0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...      1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...      0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [6]:
data.dtypes

tenure      float64
age         float64
address     float64
income      float64
ed          float64
employ      float64
equip       float64
callcard    float64
wireless    float64
longmon     float64
tollmon     float64
equipmon    float64
cardmon     float64
wiremon     float64
longten     float64
tollten     float64
cardten     float64
voice       float64
pager       float64
internet    float64
callwait    float64
confer      float64
ebill       float64
loglong     float64
logtoll     float64
lninc       float64
custcat     float64
churn       float64
dtype: object

In [8]:
data.describe()

tenure         age     address       income         ed     employ  \
count  200.000000  200.000000  200.000000   200.000000  200.00000  200.00000   
mean    35.505000   41.165000   11.650000    75.130000    2.82500   10.22500   
std     21.640971   13.076803   10.158419   128.430468    1.28555    8.95743   
min      1.000000   19.000000    0.000000     9.000000    1.00000    0.00000   
25%     16.750000   31.000000    3.000000    31.000000    2.00000    3.00000   
50%     33.500000   40.000000    9.000000    48.000000    3.00000    7.50000   
75%     55.250000   51.000000   18.000000    80.000000    4.00000   17.00000   
max     72.000000   76.000000   48.000000  1668.000000    5.00000   44.00000   

            equip    callcard    wireless    longmon     ...           pager  \
count  200.000000  200.000000  200.000000  200.00000     ...      200.000000   
mean     0.425000    0.705000    0.290000   11.78925     ...        0.275000   
std      0.495584    0.457187    0.454901    9.88725     ...        0.447635   
min      0.000000    0.000000    0.000000    1.10000     ...        0.000000   
25%      0.000000    0.000000    0.000000    5.53750     ...        0.000000   
50%      0.000000    1.000000    0.000000    8.25000     ...        0.000000   
75%      1.000000    1.000000    1.000000   14.30000     ...        1.000000   
max      1.000000    1.000000    1.000000   62.30000     ...        1.000000   

         internet   callwait      confer       ebill     loglong     logtoll  \
count  200.000000  200.00000  200.000000  200.000000  200.000000  200.000000   
mean     0.440000    0.45500    0.460000    0.440000    2.193285    3.229185   
std      0.497633    0.49922    0.499648    0.497633    0.731282    0.281019   
min      0.000000    0.00000    0.000000    0.000000    0.095000    1.749000   
25%      0.000000    0.00000    0.000000    0.000000    1.711750    3.226500   
50%      0.000000    0.00000    0.000000    0.000000    2.110000    3.240000   
75%      1.000000    1.00000    1.000000    1.000000    2.660000    3.240000   
max      1.000000    1.00000    1.000000    1.000000    4.132000    4.227000   

            lninc     custcat       churn  
count  200.000000  200.000000  200.000000  
mean     3.951015    2.475000    0.290000  
std      0.752553    1.079445    0.454901  
min      2.197000    1.000000    0.000000  
25%      3.434000    2.000000    0.000000  
50%      3.871000    2.000000    0.000000  
75%      4.382000    3.000000    1.000000  
max      7.419000    4.000000    1.000000  

[8 rows x 28 columns]

Making the data type as integer for the scikitlearn

In [13]:
data= data[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless','churn']]
data.head()
data['churn']= data['churn'].astype(int)

In [15]:
print(data.shape)
print(data.columns)

(200, 10)
Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'churn'],
      dtype='object')


Defining the X data set as np array

In [18]:
X= np.asarray(data[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])

In [19]:
X[0:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.]])

Defining the y 

In [20]:
y= np.asarray(data[['churn']])
y[0:5]

array([[1],
       [1],
       [0],
       [0],
       [0]])

We need to normalize the data to make the varience to min

In [24]:
from sklearn import preprocessing
X= preprocessing.StandardScaler().fit(X).transform(X)

In [25]:
X[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695]])

## Train/Test Split

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
Xtrain,Xtest,ytrain,ytest= train_test_split(X,y,test_size=0.3,random_state=4)

In [28]:
print(Xtrain.shape,Xtest.shape)
print(ytrain.shape,ytest.shape)

(140, 7) (60, 7)
(140, 1) (60, 1)


## Logistic regression 

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [45]:
LR = LogisticRegression(C= 0.01,solver= 'newton-cg').fit(Xtrain,ytrain)

C:\Users\CTS\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [46]:
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='newton-cg',
          tol=0.0001, verbose=0, warm_start=False)

In [47]:
yhat= LR.predict(Xtest)

In [48]:
yhat[0:5]

array([0, 0, 0, 0, 0])

defining the yhatprob which give all the classes belongs to the y = 1 and y= 0, the first colums is for y= 1 and second for the y =0

In [49]:
yhat_prob= LR.predict_proba(Xtest)

yhat_prob

array([[0.69209607, 0.30790393],
       [0.75505175, 0.24494825],
       [0.71963349, 0.28036651],
       [0.77138492, 0.22861508],
       [0.72100457, 0.27899543],
       [0.7150942 , 0.2849058 ],
       [0.67719317, 0.32280683],
       [0.75395633, 0.24604367],
       [0.56663891, 0.43336109],
       [0.77526753, 0.22473247],
       [0.72719246, 0.27280754],
       [0.76901697, 0.23098303],
       [0.63945215, 0.36054785],
       [0.58312838, 0.41687162],
       [0.79866353, 0.20133647],
       [0.71016722, 0.28983278],
       [0.67326063, 0.32673937],
       [0.63906116, 0.36093884],
       [0.64639861, 0.35360139],
       [0.67875511, 0.32124489],
       [0.76201657, 0.23798343],
       [0.68806905, 0.31193095],
       [0.77827233, 0.22172767],
       [0.68008542, 0.31991458],
       [0.66400471, 0.33599529],
       [0.82850612, 0.17149388],
       [0.70592925, 0.29407075],
       [0.6811529 , 0.3188471 ],
       [0.67397579, 0.32602421],
       [0.83274557, 0.16725443],
       [0.

In [50]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(ytest, yhat)

0.7166666666666667

In [51]:

from sklearn.metrics import classification_report
print(classification_report(ytest,yhat))

              precision    recall  f1-score   support

           0       0.72      1.00      0.83        43
           1       0.00      0.00      0.00        17

   micro avg       0.72      0.72      0.72        60
   macro avg       0.36      0.50      0.42        60
weighted avg       0.51      0.72      0.60        60



C:\Users\CTS\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [52]:
from sklearn.metrics import log_loss
log_loss(ytest, yhat_prob)

0.532105130526188